version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/authorization-microservice:1"
        LoadBalancerInfo:
          ContainerName: "authorization-microservice"
          ContainerPort: "80"

        PlatformVersion: "LATEST"